# medical_words.py

search_words = [
    "sore",
    "cough",
    "fever",
    "headache",
    "nausea",
    "vomiting",
    "dizziness",
    "chills",
    "fatigue",
    "shortness of breath",
    "stomach ache",
    "diarrhea",
    "constipation",
    "muscle pain",
    "joint pain",
    "rash",
    "swelling",
    "coughing",
    "breathing difficulties",
    "chest pain",
    "colds",
    "flu",
    "infection",
    "allergy",
    "asthma",
    "cold",
    "sore throat",
    "congestion",
    "runny nose",
    "earache",
    "nosebleed",
    "heartburn",
    "ulcer",
    "arthritis",
    "back pain",
    "indigestion",
    "bloody stool",
    "blood in urine",
    "dyspepsia",
    "insomnia",
    "anxiety",
    "depression",
    "stress",
    "hypertension",
    "high blood pressure",
    "low blood pressure",
    "diabetes",
    "hypoglycemia",
    "hyperglycemia",
    "cancer",
    "stroke",
    "heart attack",
    "kidney disease",
    "liver disease",
    "asthma attack",
    "seizures",
    "epilepsy",
    "tinnitus",
    "sinusitis",
    "bronchitis",
    "pneumonia",
    "arthritis",
    "eczema",
    "psoriasis",
    "vitamin deficiency",
    "malnutrition",
    "skin infection",
    "respiratory infection",
    "urinary tract infection",
    "UTI",
    "menstrual cramps",
    "pregnancy",
    "miscarriage",
    "stillbirth",
    "postpartum",
    "migraines",
    "fibromyalgia",
    "autoimmune",
    "heart disease",
    "gastroenteritis",
    "liver cirrhosis",
    "gallstones",
    "pneumothorax",
    "blood clot",
    "sepsis",
    "hemorrhoids",
    "hemorrhage",
    "abdominal pain",
    "palliative care",
    "chronic pain",
    "medication side effects",
    "dehydration",
    "cold sores",
    "herpes",
    "HIV",
    "AIDS",
    "chronic fatigue syndrome",
    "hypothyroidism",
    "hyperthyroidism",
    "lupus",
    "multiple sclerosis",
    "Parkinson's disease",
    "Alzheimer's",
    "dementia",
    "autism",
    "schizophrenia",
    "anorexia",
    "bulimia",
    "obesity",
    "sleep apnea",
    "snoring",
    "insomnia",
    "night sweats",
    "liver transplant",
    "surgery recovery",
    "blood pressure medication",
    "insulin",
    "antibiotics",
    "painkillers",
    "antidepressants",
    "antihistamines",
    "steroid medication",
    "immunosuppressants",
    "antiviral",
    "vaccination",
    "vaccine",
    "mental health",
    "rehabilitation",
    "physical therapy",
    "mental health counseling",
    "psychiatric care",
    "addiction",
    "drug withdrawal",
    "pain management",
    "chronic illness",
    "hello",
]
