from django.db import models


class ChatMessage(models.Model):
    """
    A model representing a chat message exchange between the user and the bot.

    Fields:
        - user_message (TextField): The message sent by the user.
        - bot_response (TextField): The response generated by the bot.
        - timestamp (DateTimeField): The date and time when the chat message
        was created.

    Methods:
        - __str__: Returns a string representation of the message exchange,
        including the user message and timestamp.
    """

    # The message sent by the user
    user_message = models.TextField()

    # The response generated by the bot
    bot_response = models.TextField()

    # The timestamp when the message was created
    # (automatically set to the current time when a new message is created)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns a string representation of the chat message.

        The string will include the user's message and the timestamp when the
        message was created.
        """
        return f"User: {self.user_message} | Bot: {self.bot_response}"
